apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web

spec:
  replicas: 1

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          imagePullPolicy: Always

          env:
            - name: APP_MESSAGE
              value: "Hello from app.yaml"

            - name: DB_PASSWORD
              value: "cGFzc3dvcmQ="

          ports:
            - containerPort: 80
---
